name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build application for Windows
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run make:win

      - name: Publish application
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish

  build_mac:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build application for macOS
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run make:mac

      - name: Publish application
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish

  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build application for Linux
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run make:linux

      - name: Publish application
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish
